global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # OTel Collector metrics endpoint (exporter prometheus)
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # Quando seus servi√ßos Spring Boot existirem, descomente e ajuste portas:
  # - job_name: "order-service"
  #   metrics_path: "/actuator/prometheus"
  #   static_configs:
  #     - targets: ["order-service:8080"]